# Generated by Django 3.2 on 2021-04-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='review',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
