# Generated by Django 3.2 on 2021-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='region',
        ),
        migrations.AddField(
            model_name='article',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, related_name='article', to='news.Region'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
