# Generated by Django 3.2 on 2021-04-14 04:52

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210413_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.photo_upload_path),
        ),
    ]
