# Generated by Django 3.2 on 2021-04-14 06:40

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to=news.models.photo_upload_path),
            preserve_default=False,
        ),
    ]
